### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by mupsje** [GeorgeQuantAnalyst/crypto-price-downloader#8]
Hi, I love your work.

Can you add Bybit and WOO network in the near future ? 
Thanks allot

greets Remco from Holland

**Comment by GeorgeQuantAnalyst** [comment]
Hello,
I'm glad that the program works for you, I plan add support for Bybit this month (November 2022).
WOO coin and other coins you will be set in "data/bybit_futures.csv"

**Comment by GeorgeQuantAnalyst** [comment]
Hello,

We add support for download futures price from Bybit exchange.

We were unable to add price downloads from WOO exchange because the CCXT library (library for download and place trades on crypto exchanges) does not support the woo exchange actually.
